Sprint13-Add Controllers
solarMal/java-shareit pull request #1
Opened 2023-08-25 14:54 UTC by solarMal

2023-08-26 03:42 UTC, z8q requested changes

2023-08-26 03:42 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +public class UserMapper {
Для маппинга еще иногда используют mapstruct,
можно посмотреть, возможно понравится подход

2023-08-26 03:42 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +            return null;
Можно подумать про то, чтобы бросать здесь какое-нибудь свое исключение.
Создать класс, который бы перехватывал исключения. Это работает через аннотацию `@ExceptionHandler`
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc
https://www.baeldung.com/exception-handling-for-rest-with-spring

И там задавать определенное сообщение ошибки (сообщение можно доставать их перехватываемого исключения) и http-статус

2023-08-26 03:42 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestBody ItemDto updatedItem) {
Вероятно здесь тоже будет нужен `@Valid`

2023-08-26 03:42 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +            return null;
Потому что сейчас описание ошибки приходит только в логах.
Можно было бы еще передавать в возвращаемом объекте

2023-08-26 03:42 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<UserDto> updateUser(@PathVariable Long id, @RequestBody UserDto userDto) {
Тут на dto нужна аннотация `@Valid`.
Сейчас есть возможность сохранить пустые поля name и email при патче

2023-08-27 08:57 UTC, solarMal commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestBody ItemDto updatedItem) {
если тут поставить валидацию, будет много ошибок

2023-08-27 09:28 UTC, solarMal commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<UserDto> updateUser(@PathVariable Long id, @RequestBody UserDto userDto) {
я сделал проверки в методе public UserDto updateUser(Long id, UserDto updatedUser)
почему то с @Valid становится куча ошибок

2023-08-27 10:44 UTC, z8q approved these changes

2023-08-30 06:20 UTC, merged